[project]
name = "intelligent-customer-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "llama-index-core>=0.14.12",
    "myapplication>=0.1.0",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.40.0",
]
